export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';

export const GET_MEDICINES = 'GET_MEDICINES'
export const POST_MEDICINE = 'POST_MEDICINE'
export const DELETE_MEDICINE = 'DELETE_MEDICINE'
export const UPDATE_MEDICINE = 'UPDATE_MEDICINE'