export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';

export const GET_MEDICINES = 'GET_MEDICINES'
export const POST_MEDICINE = 'POST_MEDICINE'
export const DELETE_MEDICINE = 'DELETE_MEDICINE'
export const UPDATE_MEDICINE = 'UPDATE_MEDICINE'
export const LOAD_MEDICINE = 'LOAD_MEDICINE'
export const ERROR_MEDICINE = 'ERROR_MEDICINE'

export const GET_DOCTORS = 'GET_DOCTORS'
export const POST_DOCTORS = 'POST_DOCTORS'
export const DELETE_DOCTORS = 'DELETE_DOCTORS'
export const UPDATE_DOCTORS = 'UPDATE_DOCTORS'

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const FORGET_REQUEST = 'FORGET_REQUEST'

export const LOGGEDIN_USER = 'LOGGEDIN_USER'
export const LOGGEDOUT_USER = 'LOGGEDOUT_USER'